GET http://localhost:5000/product/category/T-shirt

###
POST http://localhost:5000/user
Content-Type: application/json

{
    "user_name": "jhon",
    "user_email": "jhon@gmail.com",
    "user_password": "jhon123"
}

###
PATCH http://localhost:5000/product/1
Content-Type: application/json

{
    "product_name": "T-shirt black",
    "product_type": "Shirt",
    "product_size": "S",
    "product_stock": 200,
    "product_price": 107000
}

###
DELETE  http://localhost:5000/product/2